package net.ncguy.argent.utils;


import java.io.File;
import java.io.IOException;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Created by Guy on 02/07/2016.
 */
public class ReflectionUtils {

    public static List<Field> getAllFields(Class<?> cls) {
        List<Field> list = new ArrayList<>();
        Collections.addAll(list, cls.getDeclaredFields());
        if(cls.getSuperclass() != Object.class)
            list.addAll(getAllFields(cls.getSuperclass()));
        return list;
    }

    public static List<Field> getAnnotatedFields(Class<?> cls, Class<? extends Annotation> annotation) {
        return getAllFields(cls).stream().filter(f -> f.isAnnotationPresent(annotation)).collect(Collectors.toList());
    }

    public static Field setCompletelyAccessible(Field field) throws Exception {
        field.setAccessible(true);

        Field modField = Field.class.getDeclaredField("modifiers");
        modField.setAccessible(true);
        modField.setInt(field, field.getModifiers() & ~Modifier.FINAL);

        return field;
    }

    public static void generateReflectionMethods(Class<?> cls) {
        generateReflectionMethods(new File(cls.getSimpleName()+".stub"), cls);
    }

    public static void generateReflectionMethods(File file, Class<?> cls) {
        String source = "// AUTOGENERATED\n\n";
        for (Field field : cls.getDeclaredFields())
            source += ClassWriter.generateReflectionMethod(field)+"\n";
        Path path = file.toPath();
        try {
            Files.deleteIfExists(path);
            Files.write(path, source.getBytes(), StandardOpenOption.CREATE_NEW, StandardOpenOption.CREATE, StandardOpenOption.WRITE);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}
